server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active:
      - dev
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:./hoaxify-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
hoaxify:
  upload-path: uploads-prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:hoaxify-dev
  jpa:
    hibernate:
      ddl-auto: update

hoaxify:
  upload-path: uploads-dev
---
spring:
  config:
    activate:
      on-profile: test
hoaxify:
  upload-path: uploads-test
